on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: pavelzw/provision-with-micromamba@deinit

      # Linux and macOS
      - name: Run Python
        shell: bash -l {0}
        run: |
          python -c "import numpy"

      # # Windows
      # # With Powershell:
      # - name: Run Python
      #   shell: powershell
      #   run: |
      #     python -c "import numpy"
      # # Or with cmd:
      # - name: Run cmd.exe
      #   shell: cmd /C CALL {0}
      #   run: >-
      #     micromamba info && micromamba list